### ISSUE TITLE
RaiDrive is not Reviving

### ISSUE THREAD

**Issue by jcmarchi** [RaiDrive/RaiDrive.Translation#87]
Something happened ad RaiDrive no longer revives. I click on the button to revive and it opens the dialog asking to press OK. Then, after pressed OK a Windows Dialog from UAC opens and I click YES. I can see the cursor spinning for a second (like if some task is being performed) but then nothing happens. The RaiDrive windows never changes and it never comes alive.

I've tried uninstalling and reinstalling (latest version) a couple of times. I've also tried cleaning up all traces of the application in the file system and registry before reinstalling for the third time and still no luck.

Any clue? This is a big deal breaker for many users. I'd like to find out the cause and document a solution so other people can resolve this issue instead of quit using the application...

**Comment by kazihorka** [comment]
Have you checked the status of RaiDrive service? Maybe it is not restarting (even when using "revive")?

**Comment by jcmarchi** [comment]
Yeap. Service is failing restarting...  Here the Erro Log:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="RaiDrive.Service" /> 
  <EventID Qualifiers="0">0</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-03-28T18:05:07.444889300Z" /> 
  <EventRecordID>53298</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>IT-Master</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Service cannot be started. System.IO.FileNotFoundException: Could not load file or assembly 'CBFS6Net, Version=6.1.184.0, Culture=neutral, PublicKeyToken=0f194b348c109bec' or one of its dependencies. The system cannot find the file specified. File name: 'CBFS6Net, Version=6.1.184.0, Culture=neutral, PublicKeyToken=0f194b348c109bec' at hgcNZBMVt8KUSOVcg2D.sX5qloMOLh50VhRetB6.PLmKyhyiQf(rTAZlGM0cCvZlHCpdto ) at mdWAu6M8iU9bTHVS75S.ILj2QSMPPWy8n7hZ1JC.tbnZgejv8Xd4txyvAhS(Object , Object ) at mdWAu6M8iU9bTHVS75S.ILj2QSMPPWy8n7hZ1JC.YWhNQ4Gt4H(Object , Object ) at i4eWlLMXWXlBrXrPvYF.rTAZlGM0cCvZlHCpdto.UcpjtsjglvyCOpPDYbP(Object , Object ) at i4eWlLMXWXlBrXrPvYF.rTAZlGM0cCvZlHCpdto.OnStart(String[] ) at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly ...</Data> 
  </EventData>
  </Event>

**Comment by jcmarchi** [comment]
How to resolve the "Could not load file or assembly 'CBFS6Net, Version=6.1.184.0 "? Shouldn't RaiDrive install it?

**Comment by Stanly5** [comment]
Hello @jcmarchi  and @kazihorka ,
It should be good to discuss within us in here, however please make sure technical person in RaiDrive does not keep seeing this issue pages in Github because it is only for the translation.
Therefore if you wants to get an answer from RaiDrive something about technical matter, then please use below page in RaiDrive web.
https://www.raidrive.com/contact/

Have a great day~

**Comment by shekvl** [comment]
I had the same problem, in my case it seemed to be related to McAfee Endpoint Security which prevents service from starting. The event log, in addition to the above service error, logs McAfee event like this:

EventID=1092

NT AUTHORITY\SYSTEM ran RAIDRIVE.SERVICE.X64.EXE, which tried to access C:\WINDOWS\TEMP\B0494A1F-4BD3-OWMQN5SWJPTJH+IXLICD2G==\CBFS6NET.DLL, violating the rule "Creating new executable files in the Windows folder", and was blocked. For information about how to respond to this event, see KB85494.

As I did not have control over McAfee (being in corporate environment) this was a show-stopper for me. Otherwise I would recommend making an exception for RaiDrive service in McAfee.

**Comment by Questdream** [comment]
same question as you,it's time to uninstall the  powerful software except who can help me to solve it

**Comment by Stanly5** [comment]
@shekvl , @Questdream 
Here RaiDrive/Translation is only for the translation, not technical, so likely you cannot get technical supports from here.
Please leave a message in RaiDrive web.
https://www.raidrive.com/contact/

Have a nice day~

**Comment by shekvl** [comment]
@Stanly5 I did not ask for support here as I have already contacted the RaiDrive team, I shared a possible cause of the problem (confirmed by the team) and a possible way of overcoming it. I do not see any other place for public discussion of these issues anywhere.

@Questdream if you see the McAfee Endpoint Security message in the error log and can change its configuration, I suggest adding an exception for RAIDRIVE.SERVICE.X64.EXE and see if this resolves the issue.

**Comment by Stanly5** [comment]
@shekvl 
I got it!
I was just worried about if you cannot get proper supports. I would not interrupt any communication. ^^

**Comment by shekvl** [comment]
Just a note: this problem could be caused by any antivirus software which is configured to block creating executable files in the Windows folder, it is not specific to McAfee Endpoint Security.

**Comment by Questdream** [comment]
@shekvl thank you,I have no a McAfee and can't find a error log,when I try to run RAIDRIVE.SERVICE.X64.EXE ,something terrible things happened as the picture shows below.it requires me to **_run this problem in a windows service mode_**,I have no idea to resolve it.what does it mean???QAQ
![raidrive revive](https://user-images.githubusercontent.com/38719088/56795570-58988980-6843-11e9-8c49-06c7fa06f40b.png)

**Comment by shekvl** [comment]
@Questdream this is something completely different, my answer was related to the original error posted by @jcmarchi, so I cannot be of any help here.

**Comment by Questdream** [comment]
> @Questdream this is something completely different, my answer was related to the original error posted by @jcmarchi, so I cannot be of any help here.

Yeh,thanks a lot ,
it just like I have find a new problem,T^T

**Comment by jcmarchi** [comment]
Sorry for my disappearance. I was out of town for a couple of weeks.

After debugging all I could, I wasn't able to determine if the problem was in fact in the RaiDrive or in the Windows to some extent. 

At this point, I honestly believe it was one of many "failed Windows Updates" that caused the issues. 

Most people are unaware but Windows Updates are responsible for breaking the system more often than it fixes it, but most of the times either remediation is issued before damages become extensive or problems are auto-fixed in the next reboot, allowing incidents to pass unnoticed to most (other than the fact Windows - sometimes - takes longer than usual to reboot. Now you know why!!!).

What I know for sure is that RaiDrive was failing due to something in the system that was either not responding or blocking the access, and as I try to fix the problems it became worse and worse, to the point of catastrophic failure. :) 

Gladly it is what I do in general, and it was nothing more than another recovery of a system from a previous backup.

One thing I would say that made me very happy and which is the reason I am replying to this thread now: there was no corruption of the remote system! While I believe it was in part lucky of mine, I also believe RaiDrive is well done enough to only write something in the client when the communication is securely established. Props to you, guys!!

**Comment by CollinChaffin** [comment]
Um, no - it's actually a pretty bad code error.  After all the comments the answer is in the above comment from @shekvl.  The assembly simply NEVER gets copied - EVER due to the bad directory naming in Temp chosen (an encoded string?) of `"%TEMP%\b0494a1f-4bd3-owMQN5swJPTJH+ixLIcd2g=="`.

Whatever other routines need to actually pick that unpacked file up, don't as on EVERY install I've tested I have a lingering folder in TEMP named `b0494a1f-4bd3-owMQN5swJPTJH+ixLIcd2g==` with one uncopied file in it - the required `CBFS6Net.dll`.
